name: projet_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0
  google_fonts: ^2.3.1
  flutter_speed_dial: ^4.3.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  hexcolor: ^2.0.6
  shared_preferences:
  url_launcher: ^6.1.2
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.0.1
  settings_ui:
  geolocator: ^8.2.1
  rflutter_alert: ^2.0.4
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1bded1"
  image: assets/images/logo.png
  android: true
  ios: true
flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Black.ttf
      - asset: assets/fonts/Poppins-BlackItalic.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-BoldItalic.ttf
      - asset: assets/fonts/Poppins-ExtraBold.ttf
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
      - asset: assets/fonts/Poppins-ExtraLight.ttf
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
      - asset: assets/fonts/Poppins-Italic.ttf
      - asset: assets/fonts/Poppins-Light.ttf
      - asset: assets/fonts/Poppins-LightItalic.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins-MediumItalic.ttf
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
      - asset: assets/fonts/Poppins-Thin.ttf
      - asset: assets/fonts/Poppins-ThinItalic.ttf